// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/codesphere-cloud/managed-services-lib/pkg/model"
	mock "github.com/stretchr/testify/mock"

	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

	v1 "k8s.io/api/core/v1"
)

// MockKubernetesClient is an autogenerated mock type for the KubernetesClient type
type MockKubernetesClient struct {
	mock.Mock
}

type MockKubernetesClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKubernetesClient) EXPECT() *MockKubernetesClient_Expecter {
	return &MockKubernetesClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, api, namespace, obj
func (_m *MockKubernetesClient) Create(ctx context.Context, api model.APIResource, namespace string, obj *unstructured.Unstructured) (*unstructured.Unstructured, error) {
	ret := _m.Called(ctx, api, namespace, obj)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *unstructured.Unstructured
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.APIResource, string, *unstructured.Unstructured) (*unstructured.Unstructured, error)); ok {
		return rf(ctx, api, namespace, obj)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.APIResource, string, *unstructured.Unstructured) *unstructured.Unstructured); ok {
		r0 = rf(ctx, api, namespace, obj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unstructured.Unstructured)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.APIResource, string, *unstructured.Unstructured) error); ok {
		r1 = rf(ctx, api, namespace, obj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKubernetesClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockKubernetesClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - api model.APIResource
//   - namespace string
//   - obj *unstructured.Unstructured
func (_e *MockKubernetesClient_Expecter) Create(ctx interface{}, api interface{}, namespace interface{}, obj interface{}) *MockKubernetesClient_Create_Call {
	return &MockKubernetesClient_Create_Call{Call: _e.mock.On("Create", ctx, api, namespace, obj)}
}

func (_c *MockKubernetesClient_Create_Call) Run(run func(ctx context.Context, api model.APIResource, namespace string, obj *unstructured.Unstructured)) *MockKubernetesClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.APIResource), args[2].(string), args[3].(*unstructured.Unstructured))
	})
	return _c
}

func (_c *MockKubernetesClient_Create_Call) Return(_a0 *unstructured.Unstructured, _a1 error) *MockKubernetesClient_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKubernetesClient_Create_Call) RunAndReturn(run func(context.Context, model.APIResource, string, *unstructured.Unstructured) (*unstructured.Unstructured, error)) *MockKubernetesClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSecret provides a mock function with given fields: ctx, namespace, secret
func (_m *MockKubernetesClient) CreateSecret(ctx context.Context, namespace string, secret *v1.Secret) (*v1.Secret, error) {
	ret := _m.Called(ctx, namespace, secret)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecret")
	}

	var r0 *v1.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1.Secret) (*v1.Secret, error)); ok {
		return rf(ctx, namespace, secret)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1.Secret) *v1.Secret); ok {
		r0 = rf(ctx, namespace, secret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1.Secret) error); ok {
		r1 = rf(ctx, namespace, secret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKubernetesClient_CreateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecret'
type MockKubernetesClient_CreateSecret_Call struct {
	*mock.Call
}

// CreateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - secret *v1.Secret
func (_e *MockKubernetesClient_Expecter) CreateSecret(ctx interface{}, namespace interface{}, secret interface{}) *MockKubernetesClient_CreateSecret_Call {
	return &MockKubernetesClient_CreateSecret_Call{Call: _e.mock.On("CreateSecret", ctx, namespace, secret)}
}

func (_c *MockKubernetesClient_CreateSecret_Call) Run(run func(ctx context.Context, namespace string, secret *v1.Secret)) *MockKubernetesClient_CreateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1.Secret))
	})
	return _c
}

func (_c *MockKubernetesClient_CreateSecret_Call) Return(_a0 *v1.Secret, _a1 error) *MockKubernetesClient_CreateSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKubernetesClient_CreateSecret_Call) RunAndReturn(run func(context.Context, string, *v1.Secret) (*v1.Secret, error)) *MockKubernetesClient_CreateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, ref
func (_m *MockKubernetesClient) Delete(ctx context.Context, ref model.ResourceRef) error {
	ret := _m.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ResourceRef) error); ok {
		r0 = rf(ctx, ref)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKubernetesClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockKubernetesClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ref model.ResourceRef
func (_e *MockKubernetesClient_Expecter) Delete(ctx interface{}, ref interface{}) *MockKubernetesClient_Delete_Call {
	return &MockKubernetesClient_Delete_Call{Call: _e.mock.On("Delete", ctx, ref)}
}

func (_c *MockKubernetesClient_Delete_Call) Run(run func(ctx context.Context, ref model.ResourceRef)) *MockKubernetesClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ResourceRef))
	})
	return _c
}

func (_c *MockKubernetesClient_Delete_Call) Return(_a0 error) *MockKubernetesClient_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKubernetesClient_Delete_Call) RunAndReturn(run func(context.Context, model.ResourceRef) error) *MockKubernetesClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecret provides a mock function with given fields: ctx, namespace, name
func (_m *MockKubernetesClient) DeleteSecret(ctx context.Context, namespace string, name string) error {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKubernetesClient_DeleteSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecret'
type MockKubernetesClient_DeleteSecret_Call struct {
	*mock.Call
}

// DeleteSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockKubernetesClient_Expecter) DeleteSecret(ctx interface{}, namespace interface{}, name interface{}) *MockKubernetesClient_DeleteSecret_Call {
	return &MockKubernetesClient_DeleteSecret_Call{Call: _e.mock.On("DeleteSecret", ctx, namespace, name)}
}

func (_c *MockKubernetesClient_DeleteSecret_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockKubernetesClient_DeleteSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockKubernetesClient_DeleteSecret_Call) Return(_a0 error) *MockKubernetesClient_DeleteSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKubernetesClient_DeleteSecret_Call) RunAndReturn(run func(context.Context, string, string) error) *MockKubernetesClient_DeleteSecret_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, ref
func (_m *MockKubernetesClient) Get(ctx context.Context, ref model.ResourceRef) (*unstructured.Unstructured, error) {
	ret := _m.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *unstructured.Unstructured
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ResourceRef) (*unstructured.Unstructured, error)); ok {
		return rf(ctx, ref)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ResourceRef) *unstructured.Unstructured); ok {
		r0 = rf(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unstructured.Unstructured)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ResourceRef) error); ok {
		r1 = rf(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKubernetesClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockKubernetesClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ref model.ResourceRef
func (_e *MockKubernetesClient_Expecter) Get(ctx interface{}, ref interface{}) *MockKubernetesClient_Get_Call {
	return &MockKubernetesClient_Get_Call{Call: _e.mock.On("Get", ctx, ref)}
}

func (_c *MockKubernetesClient_Get_Call) Run(run func(ctx context.Context, ref model.ResourceRef)) *MockKubernetesClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ResourceRef))
	})
	return _c
}

func (_c *MockKubernetesClient_Get_Call) Return(_a0 *unstructured.Unstructured, _a1 error) *MockKubernetesClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKubernetesClient_Get_Call) RunAndReturn(run func(context.Context, model.ResourceRef) (*unstructured.Unstructured, error)) *MockKubernetesClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetPodLogs provides a mock function with given fields: ctx, namespace, podName, container, tailLines
func (_m *MockKubernetesClient) GetPodLogs(ctx context.Context, namespace string, podName string, container string, tailLines int64) (string, error) {
	ret := _m.Called(ctx, namespace, podName, container, tailLines)

	if len(ret) == 0 {
		panic("no return value specified for GetPodLogs")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64) (string, error)); ok {
		return rf(ctx, namespace, podName, container, tailLines)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64) string); ok {
		r0 = rf(ctx, namespace, podName, container, tailLines)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int64) error); ok {
		r1 = rf(ctx, namespace, podName, container, tailLines)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKubernetesClient_GetPodLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPodLogs'
type MockKubernetesClient_GetPodLogs_Call struct {
	*mock.Call
}

// GetPodLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - podName string
//   - container string
//   - tailLines int64
func (_e *MockKubernetesClient_Expecter) GetPodLogs(ctx interface{}, namespace interface{}, podName interface{}, container interface{}, tailLines interface{}) *MockKubernetesClient_GetPodLogs_Call {
	return &MockKubernetesClient_GetPodLogs_Call{Call: _e.mock.On("GetPodLogs", ctx, namespace, podName, container, tailLines)}
}

func (_c *MockKubernetesClient_GetPodLogs_Call) Run(run func(ctx context.Context, namespace string, podName string, container string, tailLines int64)) *MockKubernetesClient_GetPodLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(int64))
	})
	return _c
}

func (_c *MockKubernetesClient_GetPodLogs_Call) Return(_a0 string, _a1 error) *MockKubernetesClient_GetPodLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKubernetesClient_GetPodLogs_Call) RunAndReturn(run func(context.Context, string, string, string, int64) (string, error)) *MockKubernetesClient_GetPodLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecret provides a mock function with given fields: ctx, namespace, name
func (_m *MockKubernetesClient) GetSecret(ctx context.Context, namespace string, name string) (*v1.Secret, error) {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 *v1.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1.Secret, error)); ok {
		return rf(ctx, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1.Secret); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKubernetesClient_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type MockKubernetesClient_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockKubernetesClient_Expecter) GetSecret(ctx interface{}, namespace interface{}, name interface{}) *MockKubernetesClient_GetSecret_Call {
	return &MockKubernetesClient_GetSecret_Call{Call: _e.mock.On("GetSecret", ctx, namespace, name)}
}

func (_c *MockKubernetesClient_GetSecret_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockKubernetesClient_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockKubernetesClient_GetSecret_Call) Return(_a0 *v1.Secret, _a1 error) *MockKubernetesClient_GetSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKubernetesClient_GetSecret_Call) RunAndReturn(run func(context.Context, string, string) (*v1.Secret, error)) *MockKubernetesClient_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *MockKubernetesClient) List(ctx context.Context, opts model.ListOptions) (*unstructured.UnstructuredList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *unstructured.UnstructuredList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ListOptions) (*unstructured.UnstructuredList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ListOptions) *unstructured.UnstructuredList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unstructured.UnstructuredList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKubernetesClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockKubernetesClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts model.ListOptions
func (_e *MockKubernetesClient_Expecter) List(ctx interface{}, opts interface{}) *MockKubernetesClient_List_Call {
	return &MockKubernetesClient_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *MockKubernetesClient_List_Call) Run(run func(ctx context.Context, opts model.ListOptions)) *MockKubernetesClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ListOptions))
	})
	return _c
}

func (_c *MockKubernetesClient_List_Call) Return(_a0 *unstructured.UnstructuredList, _a1 error) *MockKubernetesClient_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKubernetesClient_List_Call) RunAndReturn(run func(context.Context, model.ListOptions) (*unstructured.UnstructuredList, error)) *MockKubernetesClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: ctx, ref, patches
func (_m *MockKubernetesClient) Patch(ctx context.Context, ref model.ResourceRef, patches []model.K8sPatch) error {
	ret := _m.Called(ctx, ref, patches)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ResourceRef, []model.K8sPatch) error); ok {
		r0 = rf(ctx, ref, patches)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKubernetesClient_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockKubernetesClient_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - ref model.ResourceRef
//   - patches []model.K8sPatch
func (_e *MockKubernetesClient_Expecter) Patch(ctx interface{}, ref interface{}, patches interface{}) *MockKubernetesClient_Patch_Call {
	return &MockKubernetesClient_Patch_Call{Call: _e.mock.On("Patch", ctx, ref, patches)}
}

func (_c *MockKubernetesClient_Patch_Call) Run(run func(ctx context.Context, ref model.ResourceRef, patches []model.K8sPatch)) *MockKubernetesClient_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ResourceRef), args[2].([]model.K8sPatch))
	})
	return _c
}

func (_c *MockKubernetesClient_Patch_Call) Return(_a0 error) *MockKubernetesClient_Patch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKubernetesClient_Patch_Call) RunAndReturn(run func(context.Context, model.ResourceRef, []model.K8sPatch) error) *MockKubernetesClient_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKubernetesClient creates a new instance of MockKubernetesClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKubernetesClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKubernetesClient {
	mock := &MockKubernetesClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
